//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignPro_Api_Demo_Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignPro_Api_Demo_Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   NEW CUSTOMER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_BTN_CUSTOMER {
            get {
                return ResourceManager.GetString("IDC_BTN_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DASHBOARD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_BTN_DASHBOARD {
            get {
                return ResourceManager.GetString("IDC_BTN_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_BTN_HOME {
            get {
                return ResourceManager.GetString("IDC_BTN_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEW CUSTOMER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_BTN_NEWCUSTOMER {
            get {
                return ResourceManager.GetString("IDC_BTN_NEWCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHOW CUSTOMER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_BTN_SHOWREGISTRATION {
            get {
                return ResourceManager.GetString("IDC_BTN_SHOWREGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow Annotation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_CB_ANNOTATION {
            get {
                return ResourceManager.GetString("IDC_CB_ANNOTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow Manual Signatures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_CB_SIGNATURE {
            get {
                return ResourceManager.GetString("IDC_CB_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Text Tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_CB_TEXTTAG {
            get {
                return ResourceManager.GetString("IDC_CB_TEXTTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_CB_UPDATERESULT {
            get {
                return ResourceManager.GetString("IDC_CB_UPDATERESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   City に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_CITY {
            get {
                return ResourceManager.GetString("IDC_LABEL_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W I L L  T R U S T  B A N K に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_COMPANYNAME {
            get {
                return ResourceManager.GetString("IDC_LABEL_COMPANYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C O N S U L T A N T   P A U L   S M I T H に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_CONSULTANT {
            get {
                return ResourceManager.GetString("IDC_LABEL_CONSULTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Country に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_COUNTRY {
            get {
                return ResourceManager.GetString("IDC_LABEL_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer Registration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_CUSTOMERREGISTRATION {
            get {
                return ResourceManager.GetString("IDC_LABEL_CUSTOMERREGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   D A S H B O A R D に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_DASHBOARD {
            get {
                return ResourceManager.GetString("IDC_LABEL_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_FIRSTNAME {
            get {
                return ResourceManager.GetString("IDC_LABEL_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H O M E に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_HOME {
            get {
                return ResourceManager.GetString("IDC_LABEL_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düsseldorf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_LBLCITY {
            get {
                return ResourceManager.GetString("IDC_LABEL_LBLCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C U S T O M E R に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_NEWCUSTOMERLOWER {
            get {
                return ResourceManager.GetString("IDC_LABEL_NEWCUSTOMERLOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Customer Registration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_NEWCUSTOMERREGISTRATION {
            get {
                return ResourceManager.GetString("IDC_LABEL_NEWCUSTOMERREGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   N E W に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_NEWCUSTOMERUPPER {
            get {
                return ResourceManager.GetString("IDC_LABEL_NEWCUSTOMERUPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_PHONE {
            get {
                return ResourceManager.GetString("IDC_LABEL_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Street に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_STREET {
            get {
                return ResourceManager.GetString("IDC_LABEL_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surname に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_LABEL_SURNAME {
            get {
                return ResourceManager.GetString("IDC_LABEL_SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pdf Not Update, please check the data inserted! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_MSG_PDFNOTUPDATE {
            get {
                return ResourceManager.GetString("IDC_MSG_PDFNOTUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_TEXT_FileName {
            get {
                return ResourceManager.GetString("IDC_TEXT_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   News from your bank, new features, training and help. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_TEXTBLOCK_NEWFORM {
            get {
                return ResourceManager.GetString("IDC_TEXTBLOCK_NEWFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register a new customer: to Will Trust Bank に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_TEXTBLOCK_REGISTERNEW {
            get {
                return ResourceManager.GetString("IDC_TEXTBLOCK_REGISTERNEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your customer and settings at a glance. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDC_TEXTBLOCK_YOURCUSTOMER {
            get {
                return ResourceManager.GetString("IDC_TEXTBLOCK_YOURCUSTOMER", resourceCulture);
            }
        }
    }
}
