//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreScraping.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScoreScraping.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   HTML:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_LABEL_HTML {
            get {
                return ResourceManager.GetString("IDC_LABEL_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_LABEL_ID {
            get {
                return ResourceManager.GetString("IDC_LABEL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("IDC_LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_LABEL_TITLE {
            get {
                return ResourceManager.GetString("IDC_LABEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_LABEL_URL {
            get {
                return ResourceManager.GetString("IDC_LABEL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_LABEL_VIEW {
            get {
                return ResourceManager.GetString("IDC_LABEL_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_PBTN_EDITLIST {
            get {
                return ResourceManager.GetString("IDC_PBTN_EDITLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_PBTN_SHOWRESULT {
            get {
                return ResourceManager.GetString("IDC_PBTN_SHOWRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_PBTN_START {
            get {
                return ResourceManager.GetString("IDC_PBTN_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieving に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_TEXT_RETRIEVE {
            get {
                return ResourceManager.GetString("IDC_TEXT_RETRIEVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://usr.golfdigest.co.jp/pg/frlogin.php に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDC_TEXT_URL {
            get {
                return ResourceManager.GetString("IDC_TEXT_URL", resourceCulture);
            }
        }
    }
}
