//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4952
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USBTempMon.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("USBTempMon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   USBTempMon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_CAP_MAINWINDOW {
            get {
                return ResourceManager.GetString("IDS_CAP_MAINWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USBMeter.dll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_GLB_USBDLLNAME {
            get {
                return ResourceManager.GetString("IDS_GLB_USBDLLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kernel32 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_GLB_USER32DLLNAME {
            get {
                return ResourceManager.GetString("IDS_GLB_USER32DLLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Detect Sensor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_PBTN_DETECTSENSOR {
            get {
                return ResourceManager.GetString("IDS_PBTN_DETECTSENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set &amp;Heater ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_PBTN_HEATER {
            get {
                return ResourceManager.GetString("IDS_PBTN_HEATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set LED&amp;1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_PBTN_LED1 {
            get {
                return ResourceManager.GetString("IDS_PBTN_LED1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set LED&amp;2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_PBTN_LED2 {
            get {
                return ResourceManager.GetString("IDS_PBTN_LED2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Sensors Detected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_DETECTSENSORSTAT_NO {
            get {
                return ResourceManager.GetString("IDS_TXT_DETECTSENSORSTAT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Detected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_DETECTSENSORSTAT_YES {
            get {
                return ResourceManager.GetString("IDS_TXT_DETECTSENSORSTAT_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click Heater button ...... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_HEATERDESC {
            get {
                return ResourceManager.GetString("IDS_TXT_HEATERDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heater Status: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_HEATERSTAT {
            get {
                return ResourceManager.GetString("IDS_TXT_HEATERSTAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Humid: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_HUMID {
            get {
                return ResourceManager.GetString("IDS_TXT_HUMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_OFF {
            get {
                return ResourceManager.GetString("IDS_TXT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_ON {
            get {
                return ResourceManager.GetString("IDS_TXT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_TEMP {
            get {
                return ResourceManager.GetString("IDS_TXT_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable load DLL: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_USBDLLLOADERROR {
            get {
                return ResourceManager.GetString("IDS_TXT_USBDLLLOADERROR", resourceCulture);
            }
        }
    }
}
