//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeaceXml.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeaceXml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hit any keys! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_HITANYKEYS {
            get {
                return ResourceManager.GetString("IDS_HITANYKEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Option: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_INVALIDOPTION {
            get {
                return ResourceManager.GetString("IDS_INVALIDOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Option and Value: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_INVALIDOPTIONANDVALUE {
            get {
                return ResourceManager.GetString("IDS_INVALIDOPTIONANDVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge completed. {0} files, Elaped Time: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MERGECOMPLETED {
            get {
                return ResourceManager.GetString("IDS_MERGECOMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MERGESTART {
            get {
                return ResourceManager.GetString("IDS_MERGESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No options were input: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_NOOPTION {
            get {
                return ResourceManager.GetString("IDS_NOOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   see help contents by executing {1} /v:on に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_SEEHELP {
            get {
                return ResourceManager.GetString("IDS_SEEHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split completed. {0} files, Elaped Time: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_SPLITCOMPLETED {
            get {
                return ResourceManager.GetString("IDS_SPLITCOMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_SPLITSTART {
            get {
                return ResourceManager.GetString("IDS_SPLITSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined Option: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_UNDEFINEDOPTION {
            get {
                return ResourceManager.GetString("IDS_UNDEFINEDOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Version: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_VERSION {
            get {
                return ResourceManager.GetString("IDS_VERSION", resourceCulture);
            }
        }
    }
}
