//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebootPC.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RebootPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupBox_Mode {
            get {
                return ResourceManager.GetString("GroupBox_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Counter {
            get {
                return ResourceManager.GetString("Label_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_CounterValue {
            get {
                return ResourceManager.GetString("Label_CounterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch External App:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_ExtApp {
            get {
                return ResourceManager.GetString("Label_ExtApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_MaxCount {
            get {
                return ResourceManager.GetString("Label_MaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Messages {
            get {
                return ResourceManager.GetString("Label_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (sec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Timeout {
            get {
                return ResourceManager.GetString("Label_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A loop was reached to {0} times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_LoopEnd {
            get {
                return ResourceManager.GetString("Msg_LoopEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save+Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pbtn_Close {
            get {
                return ResourceManager.GetString("Pbtn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pbtn_FilePath {
            get {
                return ResourceManager.GetString("Pbtn_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pbtn_Reset {
            get {
                return ResourceManager.GetString("Pbtn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pbtn_Start {
            get {
                return ResourceManager.GetString("Pbtn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pbtn_Stop {
            get {
                return ResourceManager.GetString("Pbtn_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reboot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rbtn_Reboot {
            get {
                return ResourceManager.GetString("Rbtn_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shutdown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Rbtn_Shutdown {
            get {
                return ResourceManager.GetString("Rbtn_Shutdown", resourceCulture);
            }
        }
    }
}
