//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5446
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foldersize.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foldersize.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   FolderSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_CAP_MAINWINDOW {
            get {
                return ResourceManager.GetString("IDS_CAP_MAINWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Num. Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_CB_NUMFILES {
            get {
                return ResourceManager.GetString("IDS_CB_NUMFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_CB_SIZE {
            get {
                return ResourceManager.GetString("IDS_CB_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dispaly Results に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_GB_DISPLAY {
            get {
                return ResourceManager.GetString("IDS_GB_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_GB_LAYER {
            get {
                return ResourceManager.GetString("IDS_GB_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_GB_SORTORDER {
            get {
                return ResourceManager.GetString("IDS_GB_SORTORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_GB_SORTTYPE {
            get {
                return ResourceManager.GetString("IDS_GB_SORTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_PBTN_COPY {
            get {
                return ResourceManager.GetString("IDS_PBTN_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_PBTN_EXECUTE {
            get {
                return ResourceManager.GetString("IDS_PBTN_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_PBTN_FOLDERPATH {
            get {
                return ResourceManager.GetString("IDS_PBTN_FOLDERPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_PBTN_QUIT {
            get {
                return ResourceManager.GetString("IDS_PBTN_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_RBTN_ASCEND {
            get {
                return ResourceManager.GetString("IDS_RBTN_ASCEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Descend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_RBTN_DESCEND {
            get {
                return ResourceManager.GetString("IDS_RBTN_DESCEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_RBTN_FILENAME {
            get {
                return ResourceManager.GetString("IDS_RBTN_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lower Folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_RBTN_LOWER {
            get {
                return ResourceManager.GetString("IDS_RBTN_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Num. Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_RBTN_NUMFILES {
            get {
                return ResourceManager.GetString("IDS_RBTN_NUMFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_RBTN_SIZE {
            get {
                return ResourceManager.GetString("IDS_RBTN_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total This Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_RBTN_SUM {
            get {
                return ResourceManager.GetString("IDS_RBTN_SUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TXT_FOLDERPATH {
            get {
                return ResourceManager.GetString("IDS_TXT_FOLDERPATH", resourceCulture);
            }
        }
    }
}
